{
 "title": "Telegraf",
 "description": "Telegraf dashboard intended to give you a general system overview.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "label": "Datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Used",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume used percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "AVG CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") AS \"guest\", mean(\"usage_guest_nice\") AS \"guest_nice\", mean(\"usage_iowait\") AS \"iowait\", mean(\"usage_irq\") AS \"irq\", mean(\"usage_nice\") AS \"nice\", mean(\"usage_softirq\") AS \"softirq\", mean(\"usage_steal\") AS \"steal\", mean(\"usage_system\") AS \"system\", mean(\"usage_user\") AS \"user\" FROM \"autogen\".\"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "guest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "guest_nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "AVG CPU per core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT sum(\"usage_guest\")+sum(\"usage_guest_nice\") FROM \"cpu\" WHERE (\"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($__interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "!=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Load/Memory/Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "shortterm" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "midterm" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "longterm" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ],
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "blocked" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Paused Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "io_serviced_recursive_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "IOps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}